[build]
  publish   = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."voice"]
  timeout = 26

[functions."brief"]
  timeout = 20

[functions."upload"]
  timeout = 20
