[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  timeout = 26   # Netlify will clamp to your plan’s max; safe to leave

# (no redirects needed; index.html is your root)
